"""Golden-snapshot support for the corpus profile regression test.

The corpus-*independent* invariants (every file parses, zero unknown tail bytes, zero
sha/eof/size corruption, per-file counts == SAMPLE_COUNT, every "matches" == its "surfaces")
stay as explicit assertions in `CorpusProfileTest.test_invariants` — they document what must
always hold regardless of which samples are present. The corpus-*dependent* fingerprint (how
many strokes / media records / tables / shape roles / … this exact set of samples has) lives in
`tests/golden/corpus_profiles.json`, regenerated by `tests/regen_golden.py`.

This ends the "hand-edit ~30 hardcoded counts on every new sample" chore while keeping the
regression protection: an *unexpected* change still fails the snapshot test with a reviewable
per-section diff; an *intentional* one (a new sample, or a decoder change) is applied by
rerunning the regen script and reviewing the JSON diff before committing.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = ROOT / "samples"
GOLDEN_PATH = Path(__file__).resolve().parent / "golden" / "corpus_profiles.json"


def compute_reports():
    """Compute the three corpus reports once (the expensive part — build_inventory scans every
    sample). Returned as `(inventory, leads_summary, notedoc_summary)`; shared by the test's
    setUpClass and the regen script so both snapshot exactly the same computation."""
    from pysdocx.inventory import build_inventory
    from spec.tools.analyze_note_doc import collect as collect_note_doc
    from spec.tools.analyze_sdocx2pdf_leads import collect as collect_sdocx2pdf_leads

    return (
        build_inventory([SAMPLES]),
        collect_sdocx2pdf_leads([SAMPLES])["summary"],
        collect_note_doc([SAMPLES])["summary"],
    )


def _pick(d: dict, keys) -> dict:
    return {k: d[k] for k in keys}


def _normalize(obj):
    """JSON round-trip so int dict keys (e.g. end_tag_page_models {0: 14}) and any tuples compare
    stably against the loaded golden (which is always str-keyed JSON)."""
    return json.loads(json.dumps(obj, default=str))


def corpus_snapshot(inventory: dict, leads: dict, notedoc: dict) -> dict:
    """The corpus-dependent fingerprint: only the counts/distributions that legitimately change
    when samples are added or a decoder's output changes. Invariants (== 0 / == SAMPLE_COUNT /
    a == b) are deliberately NOT here — they're asserted directly in the test. Shared by the test
    and the regen script (single source of truth for *which* values are snapshotted)."""
    tail = inventory["note_tail_profiles"]
    media = inventory["media_info_profiles"]
    end_tag = inventory["end_tag_profiles"]
    geometry = inventory["payload_geometry_profiles"]
    # tail_sentinel / tail_hash_block are per-file (== SAMPLE_COUNT), asserted as invariants.
    kinds = {k: v for k, v in tail["kinds"].items() if k not in ("tail_sentinel", "tail_hash_block")}
    snapshot = {
        "leads": _pick(leads, (
            "end_tag_page_models", "note_text_surfaces", "note_text_common_frame_hits",
            "text_boxes", "text_common_frame_hits", "text_structural_frames_found",
            "text_structural_spans_match", "text_structural_frame_offs", "media_objects",
            "media_known_ref_u32_hits", "media_by_kind", "voice_clips",
            "voice_clips_linked_to_audio_media",
        )),
        "note_tail": {
            "kinds": kinds,
            "coverage_known_bytes": tail["coverage"]["known_bytes"],
            "preload_prelude_params": tail["preload_prelude_params"],
            "pen_style_tail_params": tail["pen_style_tail_params"],
            "voice_post_u64_pairs": tail["voice_post_u64_pairs"],
            "voice_media_links": tail["voice_media_links"],
            "page_id_info_relations": tail["page_id_info_relations"],
        },
        "media": _pick(media, ("records", "format_versions", "ref_counts", "is_attached", "magic", "tail_tags")),
        "end_tag": _pick(end_tag, ("payload_sizes", "format_versions", "signature_offsets", "time_relations")),
        "page_id_records": inventory["page_id_info_profiles"]["records"],
        "geometry": _pick(geometry, ("count", "by_type", "point_counts", "marker_deltas", "shape_roles")),
        "notedoc": _pick(notedoc, (
            "gap_sizes", "inline_object_surfaces", "cell_text_surfaces",
            "tables_structural", "table_cells_structural", "voice_records",
        )),
    }
    return _normalize(snapshot)


def load_golden() -> dict:
    return json.loads(GOLDEN_PATH.read_text())


def save_golden(snapshot: dict) -> None:
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(json.dumps(snapshot, indent=2, sort_keys=True) + "\n")
