//! Byte-exact structural table parser parity gate vs pysdocx.
//!
//! Compares `sdocx::note_doc::note_tables` (exposed as `metadata.note_tables`)
//! against a fixture generated by pysdocx `note_doc_tables`
//! (`tests/fixtures/note_tables_pysdocx.json`, regenerate with the sibling
//! `gen_note_tables.py`). Every decoded field is checked: table geometry
//! (bbox, col widths, row heights, width constraints, border blocks, theme
//! fill) and, per cell, position/bbox/uuid/version/styled/fill/text/span-count.
//! Skips cleanly when a sample is absent, like the other parity gates.

use std::path::{Path, PathBuf};

use sdocx::{NoteTable, TableBorder};

fn samples_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../samples")
}

fn f64s(v: &serde_json::Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn u64_at(v: &serde_json::Value, k: &str) -> u64 {
    v[k].as_u64().unwrap()
}

const TOL: f64 = 1e-3;

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= TOL
}

fn assert_floats(ctx: &str, name: &str, got: &[f64], want: &serde_json::Value) {
    let want = f64s(want);
    assert_eq!(got.len(), want.len(), "{ctx}: {name} len");
    for (g, e) in got.iter().zip(&want) {
        assert!(close(*g, *e), "{ctx}: {name} {got:?} vs {want:?}");
    }
}

fn assert_border(ctx: &str, got: &TableBorder, want: &serde_json::Value) {
    let w = want.as_array().unwrap();
    assert_eq!(
        got.argb as u64,
        w[0].as_u64().unwrap(),
        "{ctx}: border argb"
    );
    assert!(
        close(got.width as f64, w[1].as_f64().unwrap()),
        "{ctx}: border width"
    );
    assert!(
        close(got.radius_x as f64, w[2].as_f64().unwrap()),
        "{ctx}: border radius_x"
    );
    assert!(
        close(got.radius_y as f64, w[3].as_f64().unwrap()),
        "{ctx}: border radius_y"
    );
}

fn assert_table(ctx: &str, got: &NoteTable, want: &serde_json::Value) {
    assert_eq!(got.uuid, want["uuid"].as_str().unwrap(), "{ctx}: uuid");
    assert_eq!(
        got.page_width as u64,
        u64_at(want, "page_width"),
        "{ctx}: page_width"
    );
    assert_eq!(
        got.table_index as u64,
        u64_at(want, "table_index"),
        "{ctx}: table_index"
    );
    assert_eq!(got.n_rows as u64, u64_at(want, "n_rows"), "{ctx}: n_rows");
    assert_eq!(got.n_cols as u64, u64_at(want, "n_cols"), "{ctx}: n_cols");
    assert_eq!(
        got.theme_fill_argb as u64,
        u64_at(want, "theme_fill_argb"),
        "{ctx}: theme_fill"
    );
    assert!(
        close(
            got.table_width_max as f64,
            want["table_width_max"].as_f64().unwrap()
        ),
        "{ctx}: table_width_max"
    );

    let bbox = [
        got.bbox.x_min,
        got.bbox.y_min,
        got.bbox.x_max,
        got.bbox.y_max,
    ];
    assert_floats(ctx, "bbox", &bbox, &want["bbox"]);
    let widths: Vec<f64> = got.col_widths.iter().map(|&w| w as f64).collect();
    assert_floats(ctx, "col_widths", &widths, &want["col_widths"]);
    let heights: Vec<f64> = got.row_heights.iter().map(|&h| h as f64).collect();
    assert_floats(ctx, "row_heights", &heights, &want["row_heights"]);
    let cw_min: Vec<f64> = got.col_width_min.iter().map(|&w| w as f64).collect();
    assert_floats(ctx, "col_width_min", &cw_min, &want["col_width_min"]);
    let cw_max: Vec<f64> = got.col_width_max.iter().map(|&w| w as f64).collect();
    assert_floats(ctx, "col_width_max", &cw_max, &want["col_width_max"]);

    for (i, w) in want["outer_borders"].as_array().unwrap().iter().enumerate() {
        assert_border(&format!("{ctx} outer[{i}]"), &got.outer_borders[i], w);
    }
    for (i, w) in want["grid_borders"].as_array().unwrap().iter().enumerate() {
        assert_border(&format!("{ctx} grid[{i}]"), &got.grid_borders[i], w);
    }

    let want_cells = want["cells"].as_array().unwrap();
    assert_eq!(got.cells.len(), want_cells.len(), "{ctx}: cell count");
    for (i, (c, w)) in got.cells.iter().zip(want_cells).enumerate() {
        let cctx = format!("{ctx} cell[{i}]");
        assert_eq!(c.row as u64, u64_at(w, "row"), "{cctx}: row");
        assert_eq!(c.col as u64, u64_at(w, "col"), "{cctx}: col");
        assert_eq!(c.uuid, w["uuid"].as_str().unwrap(), "{cctx}: uuid");
        assert_eq!(c.version as u64, u64_at(w, "version"), "{cctx}: version");
        assert_eq!(c.styled, w["styled"].as_bool().unwrap(), "{cctx}: styled");
        assert_eq!(
            c.fill_argb as u64,
            u64_at(w, "fill_argb"),
            "{cctx}: fill_argb"
        );
        assert_eq!(c.text, w["text"].as_str().unwrap(), "{cctx}: text");
        assert_eq!(
            c.spans.len() as u64,
            u64_at(w, "n_spans"),
            "{cctx}: n_spans"
        );
        let bbox = [c.bbox.x_min, c.bbox.y_min, c.bbox.x_max, c.bbox.y_max];
        assert_floats(&cctx, "bbox", &bbox, &w["bbox"]);
    }
}

#[test]
fn note_tables_match_pysdocx() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/note_tables_pysdocx.json"))
            .expect("fixture parses");

    let mut tables_checked = 0usize;
    let mut cells_checked = 0usize;
    for (sample_name, want_tables) in fixture.as_object().unwrap() {
        let path = samples_dir().join(sample_name);
        if !path.exists() {
            eprintln!("skipping {sample_name}: sample not present");
            continue;
        }
        let reader = sdocx::open(&path).expect("open sample");
        let got = &reader.metadata().note_tables;
        let want = want_tables.as_array().unwrap();
        assert_eq!(got.len(), want.len(), "{sample_name}: table count");
        for (i, (g, e)) in got.iter().zip(want).enumerate() {
            assert_table(&format!("{sample_name} table[{i}]"), g, e);
            tables_checked += 1;
            cells_checked += g.cells.len();
        }
    }

    if tables_checked == 0 {
        eprintln!("no table samples present — nothing compared");
    } else {
        eprintln!("{tables_checked} tables / {cells_checked} cells matched pysdocx");
    }
}
