//! Shape-parser parity gate vs pysdocx.
//!
//! Compares every decoded shape on the two shape ground-truth samples against a
//! fixture generated by pysdocx (`tests/fixtures/shapes_pysdocx.json`, see the
//! generation snippet in the fixture's git history / pysdocx `parse_page`). Fields
//! compared: kind, type_code, closed, arrowhead flags, color, pen width, marker
//! bbox, and — as a geometry checksum for the flattened outline — point count,
//! centroid and points-bbox. Skips cleanly when the samples are absent (they are
//! not all committed), like the Kaitai spec gate.

use std::path::{Path, PathBuf};

use sdocx::{PageElement, Shape, ShapeKind};

fn samples_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../samples")
}

fn kind_name(kind: ShapeKind) -> &'static str {
    match kind {
        ShapeKind::Ellipse => "ellipse",
        ShapeKind::Triangle => "triangle",
        ShapeKind::Rectangle => "rectangle",
        ShapeKind::Hexagon => "hexagon",
        ShapeKind::Rhombus => "rhombus",
        ShapeKind::Trapezoid => "trapezoid",
        ShapeKind::Pentagon => "pentagon",
        ShapeKind::Star => "star",
        ShapeKind::Cross => "cross",
        ShapeKind::Heart => "heart",
        ShapeKind::RoundedRect => "rounded_rect",
        ShapeKind::Freeform => "freeform",
        ShapeKind::FreeformSmooth => "freeform_smooth",
        ShapeKind::Arrow => "arrow",
        ShapeKind::Polygon => "polygon",
    }
}

/// The comparable projection of one shape (mirrors the fixture generator).
#[derive(Debug)]
struct Row {
    kind: &'static str,
    type_code: Option<u32>,
    closed: bool,
    head_start: bool,
    head_end: bool,
    /// pysdocx defaults a failed color scan to (37, 37, 37); mirror that here.
    color: [u8; 3],
    pen_width: Option<f32>,
    bbox: [f64; 4],
    n_points: usize,
    centroid: [f64; 2],
    points_bbox: [f64; 4],
}

fn row(s: &Shape) -> Row {
    let pts = &s.points;
    let n = pts.len() as f64;
    let (sx, sy) = pts
        .iter()
        .fold((0.0, 0.0), |(ax, ay), p| (ax + p.x, ay + p.y));
    let fold = |init: f64, f: fn(f64, f64) -> f64, get: fn(&sdocx::Point) -> f64| {
        pts.iter().fold(init, |acc, p| f(acc, get(p)))
    };
    Row {
        kind: kind_name(s.kind),
        type_code: s.type_code,
        closed: s.closed,
        head_start: s.head_start,
        head_end: s.head_end,
        color: s.color.as_ref().map_or([37, 37, 37], |c| [c.r, c.g, c.b]),
        pen_width: s.pen_width,
        bbox: [s.bbox.x_min, s.bbox.y_min, s.bbox.x_max, s.bbox.y_max],
        n_points: pts.len(),
        centroid: [sx / n, sy / n],
        points_bbox: [
            fold(f64::INFINITY, f64::min, |p| p.x),
            fold(f64::INFINITY, f64::min, |p| p.y),
            fold(f64::NEG_INFINITY, f64::max, |p| p.x),
            fold(f64::NEG_INFINITY, f64::max, |p| p.y),
        ],
    }
}

fn sort_key(bbox: &[f64; 4], kind: &str) -> (i64, i64, i64, i64, String) {
    let r = |v: f64| (v * 1000.0).round() as i64;
    (
        r(bbox[0]),
        r(bbox[1]),
        r(bbox[2]),
        r(bbox[3]),
        kind.to_string(),
    )
}

const TOL: f64 = 2e-3; // fixture floats are rounded to 3 decimals

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= TOL
}

fn f64s(v: &serde_json::Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn assert_shape_matches(ctx: &str, got: &Row, want: &serde_json::Value) {
    let w = |k: &str| &want[k];
    assert_eq!(got.kind, w("kind").as_str().unwrap(), "{ctx}: kind");
    assert_eq!(
        got.type_code,
        w("type_code").as_u64().map(|v| v as u32),
        "{ctx}: type_code"
    );
    assert_eq!(got.closed, w("closed").as_bool().unwrap(), "{ctx}: closed");
    assert_eq!(
        got.head_start,
        w("head_start").as_bool().unwrap(),
        "{ctx}: head_start"
    );
    assert_eq!(
        got.head_end,
        w("head_end").as_bool().unwrap(),
        "{ctx}: head_end"
    );
    let want_color: Vec<u8> = w("color")
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as u8)
        .collect();
    assert_eq!(got.color.to_vec(), want_color, "{ctx}: color");
    match (got.pen_width, w("pen_width").as_f64()) {
        (None, None) => {}
        (Some(g), Some(e)) => assert!((g as f64 - e).abs() <= 1e-3, "{ctx}: pen_width {g} vs {e}"),
        (g, e) => panic!("{ctx}: pen_width {g:?} vs {e:?}"),
    }
    assert_eq!(
        got.n_points,
        w("n_points").as_u64().unwrap() as usize,
        "{ctx}: n_points"
    );
    for (name, got_v, want_v) in [
        ("bbox", got.bbox.to_vec(), f64s(w("bbox"))),
        ("centroid", got.centroid.to_vec(), f64s(w("centroid"))),
        (
            "points_bbox",
            got.points_bbox.to_vec(),
            f64s(w("points_bbox")),
        ),
    ] {
        for (g, e) in got_v.iter().zip(&want_v) {
            assert!(close(*g, *e), "{ctx}: {name} {got_v:?} vs {want_v:?}");
        }
    }
}

#[test]
fn shapes_match_pysdocx() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/shapes_pysdocx.json")).expect("fixture parses");

    let mut compared = 0usize;
    for (sample_name, pages) in fixture.as_object().unwrap() {
        let path = samples_dir().join(sample_name);
        if !path.exists() {
            eprintln!("skipping {sample_name}: sample not present");
            continue;
        }
        let mut reader = sdocx::open(&path).expect("open sample");

        for index in 0..reader.page_count() {
            let bytes = reader.page_bytes(index).expect("page bytes");
            let page = sdocx::parse_page(&bytes).expect("parse page");
            let key = format!("{}.page", page.uuid);
            let want = pages[&key]
                .as_array()
                .unwrap_or_else(|| panic!("{sample_name}: page {key} missing from fixture"));

            let mut got: Vec<Row> = page
                .elements
                .iter()
                .filter_map(|el| match el {
                    PageElement::Shape(s) => Some(row(s)),
                    _ => None,
                })
                .collect();
            got.sort_by_key(|r| sort_key(&r.bbox, r.kind));

            assert_eq!(
                got.len(),
                want.len(),
                "{sample_name} page {key}: shape count ({} vs {})",
                got.len(),
                want.len()
            );
            for (i, (g, e)) in got.iter().zip(want.iter()).enumerate() {
                assert_shape_matches(&format!("{sample_name} {key} shape[{i}]"), g, e);
                compared += 1;
            }
        }
    }

    if compared == 0 {
        eprintln!("no shape samples present — nothing compared");
    } else {
        eprintln!("{compared} shapes matched pysdocx");
    }
}
