//! Text-box-parser parity gate vs pysdocx.
//!
//! Compares every decoded text box on the corpus samples that carry any against
//! a fixture generated by pysdocx (`tests/fixtures/text_boxes_pysdocx.json` —
//! `parse_page(data)["text_boxes"]` projected per box). Fields compared: text,
//! bbox, rotation angle, frame midpoints, style runs (bold/italic/underline/
//! strikethrough), color runs, highlight runs, font-size runs, and the box-level
//! font size. Skips cleanly when the samples are absent, like the shapes gate.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use sdocx::{PageElement, RichTextBox};

fn samples_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../samples")
}

/// Minimal JSON reader for the fixture (mirrors shapes.rs' approach of not
/// pulling a serde_json dev-dependency: the fixture is machine-generated and
/// well-formed, so a small recursive-descent parser is enough).
mod json {
    use std::collections::BTreeMap;

    #[derive(Debug, Clone, PartialEq)]
    pub enum Value {
        Null,
        Bool(bool),
        Num(f64),
        Str(String),
        Arr(Vec<Value>),
        Obj(BTreeMap<String, Value>),
    }

    impl Value {
        pub fn as_f64(&self) -> f64 {
            match self {
                Value::Num(n) => *n,
                _ => panic!("not a number: {self:?}"),
            }
        }
        pub fn as_usize(&self) -> usize {
            self.as_f64() as usize
        }
        pub fn as_str(&self) -> &str {
            match self {
                Value::Str(s) => s,
                _ => panic!("not a string: {self:?}"),
            }
        }
        pub fn as_arr(&self) -> &[Value] {
            match self {
                Value::Arr(a) => a,
                _ => panic!("not an array: {self:?}"),
            }
        }
        pub fn as_obj(&self) -> &BTreeMap<String, Value> {
            match self {
                Value::Obj(o) => o,
                _ => panic!("not an object: {self:?}"),
            }
        }
        pub fn get(&self, key: &str) -> &Value {
            &self.as_obj()[key]
        }
    }

    pub fn parse(text: &str) -> Value {
        let mut p = Parser {
            bytes: text.as_bytes(),
            pos: 0,
        };
        let v = p.value();
        p.ws();
        assert_eq!(p.pos, p.bytes.len(), "trailing JSON");
        v
    }

    struct Parser<'a> {
        bytes: &'a [u8],
        pos: usize,
    }

    impl Parser<'_> {
        fn ws(&mut self) {
            while self
                .bytes
                .get(self.pos)
                .is_some_and(|b| b.is_ascii_whitespace())
            {
                self.pos += 1;
            }
        }
        fn value(&mut self) -> Value {
            self.ws();
            match self.bytes[self.pos] {
                b'{' => self.obj(),
                b'[' => self.arr(),
                b'"' => Value::Str(self.string()),
                b't' => {
                    self.pos += 4;
                    Value::Bool(true)
                }
                b'f' => {
                    self.pos += 5;
                    Value::Bool(false)
                }
                b'n' => {
                    self.pos += 4;
                    Value::Null
                }
                _ => self.num(),
            }
        }
        fn obj(&mut self) -> Value {
            let mut map = BTreeMap::new();
            self.pos += 1; // {
            self.ws();
            if self.bytes[self.pos] == b'}' {
                self.pos += 1;
                return Value::Obj(map);
            }
            loop {
                self.ws();
                let key = self.string();
                self.ws();
                self.pos += 1; // :
                let val = self.value();
                map.insert(key, val);
                self.ws();
                match self.bytes[self.pos] {
                    b',' => self.pos += 1,
                    b'}' => {
                        self.pos += 1;
                        return Value::Obj(map);
                    }
                    b => panic!("bad obj byte {b}"),
                }
            }
        }
        fn arr(&mut self) -> Value {
            let mut arr = Vec::new();
            self.pos += 1; // [
            self.ws();
            if self.bytes[self.pos] == b']' {
                self.pos += 1;
                return Value::Arr(arr);
            }
            loop {
                arr.push(self.value());
                self.ws();
                match self.bytes[self.pos] {
                    b',' => self.pos += 1,
                    b']' => {
                        self.pos += 1;
                        return Value::Arr(arr);
                    }
                    b => panic!("bad arr byte {b}"),
                }
            }
        }
        fn string(&mut self) -> String {
            assert_eq!(self.bytes[self.pos], b'"');
            self.pos += 1;
            let mut out = String::new();
            loop {
                match self.bytes[self.pos] {
                    b'"' => {
                        self.pos += 1;
                        return out;
                    }
                    b'\\' => {
                        self.pos += 1;
                        match self.bytes[self.pos] {
                            b'n' => out.push('\n'),
                            b't' => out.push('\t'),
                            b'r' => out.push('\r'),
                            b'u' => {
                                let hex =
                                    std::str::from_utf8(&self.bytes[self.pos + 1..self.pos + 5])
                                        .unwrap();
                                let cp = u32::from_str_radix(hex, 16).unwrap();
                                // The fixture is generated with ensure_ascii=False,
                                // so escaped surrogate pairs don't occur.
                                out.push(char::from_u32(cp).unwrap());
                                self.pos += 4;
                            }
                            b => out.push(b as char),
                        }
                        self.pos += 1;
                    }
                    _ => {
                        // Consume one UTF-8 scalar.
                        let s = std::str::from_utf8(&self.bytes[self.pos..]).unwrap();
                        let ch = s.chars().next().unwrap();
                        out.push(ch);
                        self.pos += ch.len_utf8();
                    }
                }
            }
        }
        fn num(&mut self) -> Value {
            let start = self.pos;
            while self
                .bytes
                .get(self.pos)
                .is_some_and(|b| b"+-.eE0123456789".contains(b))
            {
                self.pos += 1;
            }
            Value::Num(
                std::str::from_utf8(&self.bytes[start..self.pos])
                    .unwrap()
                    .parse()
                    .unwrap(),
            )
        }
    }
}

/// The comparable projection of one text box (mirrors the fixture generator):
/// runs are (style, start, end) sorted; colors/highlights/font_sizes in decode
/// order.
#[derive(Debug, PartialEq)]
struct Row {
    text: String,
    bbox: [f64; 4],
    angle_deg: f64,
    frame_midpoints: Option<Vec<[f64; 2]>>,
    runs: Vec<(String, usize, usize)>,
    colors: Vec<(usize, usize, [u8; 3])>,
    highlights: Vec<(usize, usize, [u8; 3])>,
    font_sizes: Vec<(usize, usize, f32)>,
    font_size: Option<f32>,
}

fn row_from_parsed(b: &RichTextBox) -> Row {
    let mut runs: Vec<(String, usize, usize)> = b
        .runs
        .iter()
        .map(|r| {
            let style = if r.bold {
                "bold"
            } else if r.italic {
                "italic"
            } else if r.underline {
                "underline"
            } else {
                "strikethrough"
            };
            (style.to_string(), r.start, r.end)
        })
        .collect();
    runs.sort();
    Row {
        text: b.text.clone(),
        bbox: [b.bbox.x_min, b.bbox.y_min, b.bbox.x_max, b.bbox.y_max],
        angle_deg: b.rotation_degrees.unwrap_or(0.0),
        frame_midpoints: b
            .frame_midpoints
            .map(|pts| pts.iter().map(|p| [p.x, p.y]).collect()),
        runs,
        colors: b
            .colors
            .iter()
            .map(|c| (c.start, c.end, [c.color.r, c.color.g, c.color.b]))
            .collect(),
        highlights: b
            .highlights
            .iter()
            .map(|c| (c.start, c.end, [c.color.r, c.color.g, c.color.b]))
            .collect(),
        font_sizes: b.font_sizes.iter().map(|f| (f.start, f.end, f.size)).collect(),
        font_size: b.font_size,
    }
}

fn row_from_fixture(v: &json::Value) -> Row {
    let color3 = |v: &json::Value| -> [u8; 3] {
        let a = v.as_arr();
        [a[0].as_f64() as u8, a[1].as_f64() as u8, a[2].as_f64() as u8]
    };
    let mut runs: Vec<(String, usize, usize)> = v
        .get("runs")
        .as_arr()
        .iter()
        .map(|r| {
            (
                r.get("style").as_str().to_string(),
                r.get("start").as_usize(),
                r.get("end").as_usize(),
            )
        })
        .collect();
    runs.sort();
    let bbox = v.get("bbox").as_arr();
    Row {
        text: v.get("text").as_str().to_string(),
        bbox: [
            bbox[0].as_f64(),
            bbox[1].as_f64(),
            bbox[2].as_f64(),
            bbox[3].as_f64(),
        ],
        angle_deg: v.get("angle_deg").as_f64(),
        frame_midpoints: match v.get("frame_midpoints") {
            json::Value::Null => None,
            pts => Some(
                pts.as_arr()
                    .iter()
                    .map(|p| [p.as_arr()[0].as_f64(), p.as_arr()[1].as_f64()])
                    .collect(),
            ),
        },
        runs,
        colors: v
            .get("colors")
            .as_arr()
            .iter()
            .map(|c| (c.get("start").as_usize(), c.get("end").as_usize(), color3(c.get("color"))))
            .collect(),
        highlights: v
            .get("highlights")
            .as_arr()
            .iter()
            .map(|c| (c.get("start").as_usize(), c.get("end").as_usize(), color3(c.get("color"))))
            .collect(),
        font_sizes: v
            .get("font_sizes")
            .as_arr()
            .iter()
            .map(|f| {
                (
                    f.get("start").as_usize(),
                    f.get("end").as_usize(),
                    f.get("size").as_f64() as f32,
                )
            })
            .collect(),
        font_size: match v.get("font_size") {
            json::Value::Null => None,
            n => Some(n.as_f64() as f32),
        },
    }
}

#[test]
fn text_boxes_match_pysdocx() {
    let fixture_path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/text_boxes_pysdocx.json");
    let fixture = json::parse(&std::fs::read_to_string(fixture_path).unwrap());

    let mut compared = 0usize;
    for (sample_name, pages) in fixture.as_obj() {
        let sample_path = samples_dir().join(sample_name);
        if !sample_path.exists() {
            eprintln!("skipping: {sample_name} not present");
            continue;
        }
        let mut reader = sdocx::open(&sample_path).expect("open sample");

        // Map page basename -> decoded text boxes.
        let mut by_page: BTreeMap<String, Vec<RichTextBox>> = BTreeMap::new();
        for i in 0..reader.page_count() {
            let bytes = reader.page_bytes(i).expect("page bytes");
            let page = sdocx::parse_page(&bytes).expect("parse page");
            let boxes: Vec<RichTextBox> = page
                .elements
                .iter()
                .filter_map(|el| match el {
                    PageElement::TextBox(tb) => Some(tb.clone()),
                    _ => None,
                })
                .collect();
            by_page.insert(format!("{}.page", page.uuid), boxes);
        }

        for (page_name, expected_boxes) in pages.as_obj() {
            let got = by_page
                .get(page_name)
                .unwrap_or_else(|| panic!("{sample_name}: page {page_name} not decoded"));
            let expected = expected_boxes.as_arr();
            assert_eq!(
                got.len(),
                expected.len(),
                "{sample_name} {page_name}: text box count"
            );
            // Match by text (order between the two implementations can differ).
            for exp in expected {
                let exp_row = row_from_fixture(exp);
                let got_box = got
                    .iter()
                    .find(|b| b.text == exp_row.text)
                    .unwrap_or_else(|| {
                        panic!("{sample_name} {page_name}: no box with text {:?}", exp_row.text)
                    });
                let got_row = row_from_parsed(got_box);
                assert_eq!(got_row, exp_row, "{sample_name} {page_name}");
                compared += 1;
            }
        }
    }
    // 8 boxes across 4 samples when the full corpus is present.
    assert!(compared > 0, "no fixture samples present");
    eprintln!("compared {compared} text boxes");
}
